static_cdn/project/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	post_user_list,
	)

urlpatterns = [
	url(r'^$', post_list,name='list'),
	url(r'^userposts/$', post_user_list,name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

static_cdn/project/project/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^', include("posts.urls",namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

static_cdn/project/comments/models.py
from __future__ import unicode_literals


from django.conf import settings
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


from django.db import models
# Create your models here.

class CommentManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id= obj_id)
        return qs


class Comment(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL,default=1) 
	
	content_type = models.ForeignKey(ContentType,on_delete=models.CASCADE)
	object_id=models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type','object_id')
	
	content = models.TextField()
	timestamp = models.DateTimeField(auto_now_add=True)

	objects = CommentManager()

	def __unicode__(self):
		return str(self.user.username)

	def __str__(self):
		return str(self.user.username)

static_cdn/project/posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
# Create your models here.

#Post.objects.all()
#Post.objects.create(user=user, title="Some title")
class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		#Post.objects.all() = Super(PostManager, self).all()
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())




def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

class Post(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location,
		null=True, blank=True,
		height_field="height_field",
		width_field="width_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)




	objects = PostManager()



	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail" , kwargs={"slug":self.slug})
		#return "/posts/%s/" %(self.id)

	class Meta:
		ordering = ["-timestamp", "-updated"]

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs
	
	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

def create_slug(instance,new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug=new_slug
	qs = Post.objects.filte(slug=slug)
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug,qs.first().id)
		return create_slug(instance,new_slug=new_slug)
	return slug

def pre_save_post_receiver(sender,instance,*args,**kwargs):
	slug  = slugify(instance.title)
	exists = Post.objects.filter(slug=slug).exists()
	if exists:
		slug = "%s-%s" %(slug,instance.id)

	instance.slug = slug


pre_save.connect(pre_save_post_receiver,sender=Post)

static_cdn/project/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields =[
			"title",
			"content",
			"image",
			"draft",
			"publish",
		]

static_cdn/project/posts/views.py
from urllib import quote_plus
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.shortcuts import render , get_object_or_404,redirect
from django.utils import timezone
from comments.models import Comment
# Create your views here.
from django.contrib.contenttypes.models import ContentType
from comments.forms import CommentForm
from .forms import PostForm
from .models import Post

def post_create(request):
	domain="http://"+request.META['HTTP_HOST']
	register=domain+"/register/"
	loginlink =domain+'/login/'
	logoutlink =domain+'/logout/'
	if not request.user.is_authenticated():
		return render(request,"form.html",{"message":"You must login to continue","register":register,"dashboard":domain,"loginlink":loginlink})
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		print form.cleaned_data.get("title")
		instance.user=request.user
		instance.save()
		messages.success(request,"Successfully Created")
		return HttpResponseRedirect(instance.get_absolute_url())
	context ={
		"form":form,
		"dashboard":domain,"logoutlink":logoutlink,
	}
	return render(request,"post_form.html",context )

def post_detail(request , slug=None):
	instance = get_object_or_404(Post, slug=slug)
	domain="http://"+request.META['HTTP_HOST']
	register=domain+"/register/"
	loginlink =domain+'/login/'
	logoutlink =domain+'/logout/'
	createlink = domain+'/create/'
	if instance.draft or instance.publish > timezone.now().date():
		pass
	share_string = quote_plus(instance.content)

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get('object_id')
		content_data = form.cleaned_data.get("content")
		new_comment, created = Comment.objects.get_or_create(
							user = request.user,
							content_type= content_type,
							object_id = obj_id,
							content = content_data,
						)
		

	comments = instance.comments
	context ={
		"register":register,"dashboard":domain,"loginlink":loginlink,"logoutlink":logoutlink,"createlink":createlink,
		"title" : instance.title,
		"instance" : instance,
		"share_string": share_string,
		"comments":comments,
		"comment_form":form,
	}
	return render(request,"post_detail.html",context )

def post_list(request):
	domain="http://"+request.META['HTTP_HOST']
	register=domain+"/register/"
	loginlink =domain+'/login/'
	logoutlink =domain+'/logout/'
	createlink = domain+'/create/'
	userpostlist = domain+'/userposts/'
	today = timezone.now().date()
	queryset_list = Post.objects.active()
	if request.user.is_staff or request.user.is_superuser:
		query_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			    Q(title__icontains=query)|
			    Q(content__icontains=query)|
			    Q(user__first_name__icontains=query)|
			    Q(user__last_name__icontains=query)
			    ).distinct()

	paginator = Paginator(queryset_list, 2) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context ={
		"register":register,"dashboard":domain,"loginlink":loginlink,"logoutlink":logoutlink,
		"userpostlist":userpostlist,
		"createlink":createlink,
		"object_list" : queryset,
		"title" : "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request,"post_list.html",context )



def listing(request):
    contact_list = Contacts.objects.all()
    

    return render(request, 'list.html', {'contacts': contacts})




def post_update(request,slug =None):
	instance = get_object_or_404(Post, slug=slug)
	domain="http://"+request.META['HTTP_HOST']
	register=domain+"/register/"
	loginlink =domain+'/login/'
	logoutlink =domain+'/logout/'
	if not request.user.is_authenticated():
		return render(request,"form.html",{"message":"You must login to continue","register":register,"dashboard":domain,"loginlink":loginlink})
	if request.user != instance.user:
		 return render(request,"message.html",{"message":"You cannot edit this post.","dashboard":domain,"logoutlink":logoutlink})
	form = PostForm(request.POST or None, request.FILES or None , instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request,"Successfully Saved")

		return HttpResponseRedirect(instance.get_absolute_url())
	context ={
		"title" : instance.title,
		"instance" : instance,
		"form":form,

	}
	return render(request,"post_form.html",context )

def post_delete(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	domain="http://"+request.META['HTTP_HOST']
	register=domain+"/register/"
	loginlink =domain+'/login/'
	logoutlink =domain+'/logout/'
	if not request.user.is_authenticated():
		return render(request,"form.html",{"message":"You must login to continue","register":register,"dashboard":domain,"loginlink":loginlink})
	if request.user != instance.user:
		 return render(request,"message.html",{"message":"You cannot delete this post.","dashboard":domain,"logoutlink":logoutlink})
	instance.delete()
	messages.success(request,"Successfully Deleted")
	return redirect("posts:list")


def post_user_list(request):
	domain="http://"+request.META['HTTP_HOST']
	register=domain+"/register/"
	loginlink =domain+'/login/'
	logoutlink =domain+'/logout/'
	createlink = domain+'/create/'
	userpostlist=domain+"/userposts/"
	today = timezone.now().date()
	queryset_list = Post.objects.active()
	if request.user.is_staff or request.user.is_superuser:
		query_list = Post.objects.all()

	query = request.GET.get("q")
	queryset_list = queryset_list.filter(user=request.user)

	paginator = Paginator(queryset_list, 2) # Show 2 posts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context ={
		"register":register,"dashboard":domain,"loginlink":loginlink,"logoutlink":logoutlink,"userpostlist":userpostlist,
		"createlink":createlink,
		"object_list" : queryset,
		"title" : "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request,"post_list.html",context )

static_cdn/project/templates/base.html
{% load staticfiles %}
<html>
<head>
	<title>{% block head_title %}Blog{% endblock head_title %}</title>
	<link rel="stylesheet" type="text/css" href='{% static "css/base.css" %}' />
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<style>
  html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>
<style type="text/css">
	{% block style %}{% endblock %}

</style>

{% block head_extra %}  {% endblock head_extra %}

</head>

<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



{% include "messages_display.html" %}
<div class="container">
{% block content %}

<div class="container">
{% endblock content %}
</div>
</div>
<script   src="http://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$(".content-markdown").each(function(){
			var content = $(".content-markdown").text()
			console.log(content)
			var markedContent = marked(content)
			console.log(markedContent)
			$(this).html(markedContent)
		})

		$(".content-markdown img").each(function(){
			$(this).addClass("img-responsive");
		})

		$(".post-detail-item img").each(function(){
			$(this).addClass("img-responsive");
		})

		
		//console.log(titleValue)
		var contentItem = $("#id_content");
		var contentValue = $("#id_content").val();
		$("#preview-content").html(marked(contentValue))

		var contentInput = $("#id_content");
		function setContent(value){
			var markedContent = marked(value)
			$("#preview-content").html(markedContent)
			$("#preview-content img").each(function(){
				$(this).addClass("img-responsive")
			})
			
		}
		setContent(contentInput.val())

		contentInput.keyup(function(){
			var newContent = $(this).val()
			setContent(newContent)
		})

		var titleInput = $("#id_title");
		//var titleValue = $("#id_title").val();
		

		function setTitle(value){
			$("#preview-title").text(value)
		}
		setTitle(titleInput.val())
		titleInput.keyup(function(){
			var newContent = $(this).val()
			setTitle(newContent)
		})
	})
</script>
</body>
</html>

static_cdn/project/templates/form.html
{% extends "base.html" %}


{% block content %}
<style>
  html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>
<div class="col-sm-8 col-sm-offset-2">
  <div class="row">
    <div class="container">
      <div class="col-sm-4">
        <h3 style="color:red;">{{ message }}</h3>
      </div>
      <div class="col-sm-4">
        <div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ dashboard }}"> Home </a></button>
          <button type="button" class="btn btn-default"><a href="{{ loginlink }}">Login</a><br></button>
          <button type="button" class="btn btn-default"><a href="{{ register }}">Register</a></button>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-sm-8 col-sm-offset-2">
<h4>{{ title }}</h4>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form }}
<br>
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

static_cdn/project/templates/form2.html
{% extends "base.html" %}


{% block content %}
<style>
  html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>
<div class="col-sm-8 col-sm-offset-2">
  <div class="row">
    <div class="container">
      <div class="col-sm-4">
        
      </div>
      <div class="col-sm-4">
        <div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ dashboard }}"> Home </a></button>
          <button type="button" class="btn btn-default"><a href="{{ loginlink }}">Login</a><br></button>
          <button type="button" class="btn btn-default"><a href="{{ register }}">Register</a></button>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-sm-8 col-sm-offset-2">
<h4>{{ title }}</h4>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form }}
<br>
<h3>You have been logged out.</h3>
</form>
</div>
{% endblock content %}

static_cdn/project/templates/index.html
<html>
<head>
	<style>
  html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>
</head>

<body>
	<h1>This is a {{ title }}.</h1>

{% for obj in object_list %}

{% url "posts:detail" id=obj.id %}
<a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a><br/>
{{ obj.content }}<br/>
{{ obj.timestamp }}<br/>
{{ obj.updated }}<br/>
{{ obj.id }}<br/>

{% endfor %}
</body>
</html>

static_cdn/project/templates/message.html
{% extends "base.html" %}


{% block content %}
<h3>{{ message }}</h3>
<div class='col-sm-6 col-sm-offset-3'>
<a href="{{ logoutlink }}"> Logout</a><br>
<a href="{{ dashboard }}">Home</a>
<h4>{{ title }}</h4>
<hr/>

</div>
{% endblock content %}

static_cdn/project/templates/messages_display.html
{% if messages %}
<div class="messages">

	
	<ul class="messages">
	{% for message in messages %}
	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}
	</ul>

</div>
{% endif %}

static_cdn/project/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<style>
  html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>

{% if request.user.is_authenticated %}
<div class="col-sm-8 col-sm-offset-2">
  <div class="row">
    <div class="container">
      <div class="col-sm-4">
        <h4>Welcome {{ request.user }}</h4>
      </div>
      <div class="col-sm-4">
        <div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ dashboard }}"> Home </a></button>
          <button type="button" class="btn btn-default"><a href="{{ createlink }}">Create new post</a><br></button>
          <button type="button" class="btn btn-default"><a href="{{ logoutlink }}">Logout</a></button>
        </div>
      </div>
    </div>
  </div>
</div>


{% else %}
<div class="col-sm-8 col-sm-offset-2">
  <div class="row">
    <div class="container">
      <div class="col-sm-4">
        
      </div>
      <div class="col-sm-4">
        <div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ dashboard }}"> Home </a></button>
          <button type="button" class="btn btn-default"><a href="{{ loginlink }}"> Login </a></button>
          <button type="button" class="btn btn-default"><a href="{{ register }}"> Register </a></button>
        </div>
      </div>
    </div>
  </div>
</div>

  
{% endif %}


<div class="col-sm-8 col-sm-offset-2">
	<h1>
		{{ title }}.<small> {% if instance.draft %} <span style='color:red;'>Draft</span> {% endif %}{{ instance.publish|timesince }} ago</small>
	</h1>
	<p>
		<div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ request.build_absolute_uri }}edit"> Edit </a></button>
          <button type="button" class="btn btn-default"><a href="{{ request.build_absolute_uri }}delete"> Delete </a></button>
        </div>
	</p>
	<p>Author : {{ instance.user }}</p>
	
	{% if instance.image %}
	<img src="{{ instance.image.url }}" class="img-responsive"  />
	{% endif %}
	<p>
		<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true">
			
		</div>
		<hr/>
	</p>

	<div class='row'>
		<div class='col-sm-10 col-sm-offset-1'>
			<div class='content-markdown'>
{{ instance.content}}
			</div>
			<hr/>
			<br/>

			<div>
				<p class="lead">
					Comments
				</p>
				{% if request.user.is_authenticated %}
				<form method="POST" action="."> {% csrf_token %}
	            	{{ comment_form }}
	            	<br>
	            	<input type='submit' value='Post comment' class='btn btn-default'>
	        	</form>
	        	{% else %}
	        	<p>You must login to comment</p>
	        	{% endif %}
				<hr/>
				{% for comment in comments %}
					<blockquote>
						<p>{{ comment.content }}</p>
						<footer>{{ comment.user }} on <strong>{{ comment.timestamp }}</strong></footer>
					</blockquote>
					<hr/>
				{% endfor %}
	<!--{{ comments }} 
	{{ instance.comment_set.all }}-->
			</div>

			<div class="fb-comments" data-href={{ request.build_absolute_uri }} data-numposts="5">
			</div>
		</div>

		{{ instance.updated }}<br/>
		{{ instance.id }}<br/>
<!-- <p>
<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook
</a>

<a href="https://twitter.com/home?status={{ instance.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
Twitter
</a>

<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>


<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
Linkedin
</a>
</p> -->
	</div>
</div>
{% endblock content %}	

static_cdn/project/templates/post_form.html
{% extends "base.html" %}

{% block head_extra %}  
{{ form.media }}


{% endblock head_extra %}



{% block content %}

<style>
  html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>
{% if request.user.is_authenticated %}
<div class="col-sm-12">
  <div class="row">
    <div class="container">
      <div class="col-sm-6">
        <h4>Welcome {{ request.user }}</h4>
      </div>
      <div class="col-sm-6">
        <div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ dashboard }}"> Home </a></button>
          <button type="button" class="btn btn-default"><a href="{{ logoutlink }}">Logout</a></button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-sm-5">
	<h1>Preview</h1>
<div class="content-preview">
	<h3 id="preview-title"></h3>
	<p id="preview-content"></p>
</div>
</div>

<div class="col-sm-7">
<h1>Form</h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form.as_p }}
<input type='submit' class="btn btn-default" value='Create Post' />
</form>
</div>
{% else %}
       	<p>You must login to create post.Unauthorised users are not allowed.This act will be reported and strict actions will be taken. (may be SSAC ) .</p>
{% endif %}


{% endblock content %}

static_cdn/project/templates/post_list.html
{% extends "base.html" %}

{% block content %}

<style>
  html, body {
    max-width: 100%;
    overflow-x: hidden;
}
</style>
{% if request.user.is_authenticated %}

<div class="col-sm-8 col-sm-offset-2">
  <div class="row">
    <div class="container">
      <div class="col-sm-4">
        <h4>Welcome <a href="{{ userpostlist }}">{{ request.user }}</a></h4>
      </div>
      <div class="col-sm-4">
        <div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ dashboard }}"> Home </a></button>
          <button type="button" class="btn btn-default"><a href="{{ createlink }}">Create new post</a><br></button>
          <button type="button" class="btn btn-default"><a href="{{ logoutlink }}">Logout</a></button>
        </div>
      </div>
    </div>
  </div>
</div>


{% else %}
<div class="col-sm-8 col-sm-offset-2">
  <div class="row">
    <div class="container">
      <div class="col-sm-4">
        
      </div>
      <div class="col-sm-4">
        <div class="btn-group pull-right" role="group" aria-label="...">
          <button type="button" class="btn btn-default"><a href="{{ dashboard }}"> Home </a></button>
          <button type="button" class="btn btn-default"><a href="{{ loginlink }}"> Login </a></button>
          <button type="button" class="btn btn-default"><a href="{{ register }}"> Register </a></button>
        </div>
      </div>
    </div>
  </div>
</div>

  
{% endif %}


<div class="col-sm-8 col-sm-offset-2">
  <h1></h1>
<form method='GET' action='' class="row">
<div class="col-sm-6">
    <div class="input-group">
      <input class="form-control" type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
      <span class="input-group-btn">
        <input class="btn btn-default" type='submit' value='Search'/>
      </span>
    </div>
</div>
</form>
{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">

      {% if obj.image %}
        <img src="{{ obj.image.url }}" class="img-responsive"  />
      {% endif %}
      
      <div class="caption">
        {% if obj.draft %}<h3>Staff only: Draft </h3> {% endif %} {% if obj.publish > today %}<h3> Staff Only: Future Post </h3> {% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a><small> {{ obj.publish|timesince }} </small></h3>
        
        <p class="content-markdown">{{ obj.content| truncatechars:0 }}<br/>
<br/><br/></p>
  {{ obj.updated }}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock content %}